#@ load("@ytt:data", "data")
#@ load("labels.lib.yml", "labels")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: #@ labels(data.values.name)
  name: #@ data.values.name
spec:
  replicas: #@ data.values.replicas
  selector:
    matchLabels: #@ labels(data.values.name)
  template:
    metadata:
      labels: #@ labels(data.values.name)
    spec:
      containers:
      - image: greeter
        env:
        - name: GREETING
          value: #@ data.values.greeting
        name: greeter-server
