---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greeter
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - image: greeter
        env:
        - name: GREETING
          value: "Greetings"
        name: greeter-server
