---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeter
  name: greeter
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: greeter
  type: NodePort
