#@ load("@ytt:data", "data")
#@ load("labels.lib.yml", "labels")

---
apiVersion: v1
kind: Service
metadata:
  labels: #@ labels(data.values.name)
  name: #@ data.values.name
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector: #@ labels(data.values.name)
  type: NodePort
